# Generated by Django 3.2.8 on 2021-11-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address1',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='test', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='test', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_full_name',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
