# Generated by Django 3.2.8 on 2021-11-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20211125_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_full_name',
            new_name='cardholder_full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
    ]
