# Generated by Django 3.2.8 on 2021-12-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20211204_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='106F6D7590', editable=False, max_length=10, unique=True),
        ),
    ]
