# Generated by Django 3.2.8 on 2022-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='A78D71A9B6', editable=False, max_length=10, unique=True),
        ),
    ]
