# Generated by Django 3.2.8 on 2022-01-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='1CFEC64194', editable=False, max_length=10, unique=True),
        ),
    ]
