# Generated by Django 3.2.8 on 2022-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='BB136E1835', editable=False, max_length=10, unique=True),
        ),
    ]
