# Generated by Django 3.2.11 on 2022-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0025_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='BDF5E62420', editable=False, max_length=10),
        ),
    ]
