# Generated by Django 3.2.11 on 2022-01-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0026_auto_20220121_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='57B5975086694682BFBD', editable=False, max_length=10, unique=True),
        ),
    ]
