# Generated by Django 3.2.8 on 2021-12-08 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseschedulelist', to='courses.course'),
        ),
    ]
