# Generated by Django 3.2.8 on 2021-11-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseschedule',
            old_name='course_time',
            new_name='course_start_time',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
