# Generated by Django 3.2.8 on 2021-11-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211101_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_friendly_name',
            new_name='friendly_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='main_category_friendly_name',
            new_name='friendly_name',
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='main_category_name',
            new_name='name',
        ),
    ]
