# Generated by Django 3.2.8 on 2021-12-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211208_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseschedule',
            old_name='course_id',
            new_name='course',
        ),
    ]
