# Generated by Django 3.2.8 on 2021-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseschedule_course_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='course_link',
            field=models.URLField(max_length=1024),
        ),
    ]
