# Generated by Django 3.2.8 on 2022-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_id_courseschedule_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_updated',
            field=models.TimeField(),
        ),
    ]
