# Generated by Django 3.2.8 on 2022-01-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220110_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='date_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='time_updated',
            field=models.TimeField(),
        ),
    ]
