# Generated by Django 3.2.8 on 2022-01-12 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220112_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_updated',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='date_updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='time_updated',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
