# Generated by Django 3.2.8 on 2022-01-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number_of_lectures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(),
        ),
    ]
