# Generated by Django 3.2.8 on 2022-01-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20220114_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
