# Generated by Django 3.2.8 on 2022-01-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220114_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_timezone',
            new_name='timezone',
        ),
    ]
