# Generated by Django 3.2.8 on 2022-01-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_course_timezone_course_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time_added',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_updated',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='time_added',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='time_updated',
        ),
    ]
