# Generated by Django 3.2.8 on 2021-12-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='B381D7FC7B', editable=False, max_length=10, unique=True),
        ),
    ]
