# Generated by Django 3.2.8 on 2021-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='offer_name',
            field=models.CharField(default='Discount', max_length=100),
            preserve_default=False,
        ),
    ]
